version: '3.7'

services:
  app:
    build: ./app
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '1.0'
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa
      MYSQL_DATABASE: carrosDB
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '1.0'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-admin:
    build: ./db-admin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: senha_da_nasa
    ports:
      - "81:80"
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '4.0'

volumes:
  db-data:
