CREATE DATABASE IF NOT EXISTS carrosDB;
USE carrosDB;

CREATE TABLE IF NOT EXISTS carros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    modelo VARCHAR(50) NOT NULL,
    marca VARCHAR(50) NOT NULL,
    ano INT NOT NULL,
    placa VARCHAR(10) NOT NULL,
    cor VARCHAR(20) NOT NULL,
    nro_chassi VARCHAR(50) NOT NULL
);